Create readme
TankevychO/taxi pull request #2
Opened 2021-12-14 18:16 UTC by TankevychO

2021-12-14 19:23 UTC, begemot1987 approved these changes

2021-12-15 08:15 UTC, PaulMartsiniv approved these changes

2021-12-15 08:27 UTC, Nick97-git requested changes
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> do you have /cars/all, /drivers/all, /manufacturers/all url patterns?
- remove redundant `/` in the end of url patterns like /cars/, /drivers/, /manufacturers/
- DriverDaoImpl -> move your private method after public ones
- AuthenticationServiceImpl -> remove `else`, it's redundant

2021-12-15 08:27 UTC, Nick97-git commented on README.md
> +- controllers for all actions
let's move this info to the paragraph `Implementation details and technologies` and add this info not as separate paragraphs but as text info, and make it make it shorter

2021-12-15 08:27 UTC, Nick97-git commented on README.md
> +#### Performs the following actions:
```suggestion
#### Available actions of the application
```

2021-12-15 08:27 UTC, Nick97-git commented on README.md
> +  `PATH TO app.log`
```suggestion
- [x] Change absolute path to your log file in `log4j2.xml` 
```

2021-12-15 08:27 UTC, Nick97-git commented on README.md
> +  `PATH TO checkstyle.xml` </br>
```suggestion
- [x] Change the absolute path to checkstyle.xml in `pom.xml` </br>
```

2021-12-15 08:27 UTC, Nick97-git commented on README.md
> +  `URL`, `USERNAME`, `PASSWORD`, `JDBC_DRIVER`
```suggestion
- [x] Change `URL`, `USERNAME`, `PASSWORD`, `JDBC_DRIVER` in `/util/ConnectionUtil.java` 
```

2021-12-15 09:07 UTC, Nick97-git commented
One more comment. At the moment your path looks like src/main/java/mate... We should rename "mate" to something else, like "taxi". After you do that don't forget to change the value you pass to the Injector.getInstance() everywhere you use it

2021-12-15 10:44 UTC, Nick97-git requested changes

2021-12-15 10:44 UTC, Nick97-git commented on README.md
> +- [x] Change absolute path to your log file in `log4j2.xml` </br>
```suggestion
- [x] Change the absolute path to your log file in `log4j2.xml` </br>
```

2021-12-15 10:44 UTC, Nick97-git commented on src/main/resources/log4j2.xml
> +        <Logger name="taxi.academy" level="info" additivity="false">
remove academy)

2021-12-15 11:01 UTC, Nick97-git approved these changes

2021-12-15 11:43 UTC, merged